name: Sync with Dev.to
on:
  push:
    branches:
      - master

jobs:
  operations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Syncing Article to dev.to
        uses: ful1e5/TheActionDev@v2
        with:
          api-key: ${{ secrets.DEVTO_API_KEY }} # Store your 'api-key' in Github Secret
          directory: ./posts # Your article directory
          ignore: README.md, _index.md # Markdown file you wan't to ignore. Multple files separated by ,(comma)
